# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BRConventer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        MainWindow.setWindowIcon(QtGui.QIcon('R_L.png'))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 600))
        MainWindow.setMaximumSize(QtCore.QSize(700, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputTextBox = QtWidgets.QTextEdit(self.centralwidget)
        self.inputTextBox.setGeometry(QtCore.QRect(10, 110, 301, 281))
        self.inputTextBox.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.inputTextBox.setMouseTracking(True)
        self.inputTextBox.setObjectName("inputTextBox")
        self.outputTextBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.outputTextBox.setGeometry(QtCore.QRect(390, 110, 301, 281))
        self.outputTextBox.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.outputTextBox.setMouseTracking(True)
        self.outputTextBox.setObjectName("outputTextBox")
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertButton.setGeometry(QtCore.QRect(310, 450, 81, 71))
        self.convertButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convertButton.setMouseTracking(True)
        self.convertButton.setStyleSheet("QPushButton {\n"
"    background:transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(169, 168, 181, 30);\n"
"}")
        self.convertButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("convert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.convertButton.setIcon(icon)
        self.convertButton.setIconSize(QtCore.QSize(64, 64))
        self.convertButton.setObjectName("convertButton")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(210, 10, 281, 41))
        self.header.setTextFormat(QtCore.Qt.AutoText)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.typeSelector = QtWidgets.QComboBox(self.centralwidget)
        self.typeSelector.setGeometry(QtCore.QRect(248, 61, 201, 21))
        self.typeSelector.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.typeSelector.setMouseTracking(True)
        self.typeSelector.setEditable(False)
        self.typeSelector.setDuplicatesEnabled(False)
        self.typeSelector.setObjectName("typeSelector")
        self.typeSelector.addItem("")
        self.typeSelector.addItem("")
        self.typeSelector.addItem("")
        self.pasteButton = QtWidgets.QPushButton(self.centralwidget)
        self.pasteButton.setGeometry(QtCore.QRect(140, 400, 41, 41))
        self.pasteButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pasteButton.setMouseTracking(True)
        self.pasteButton.setStyleSheet("QPushButton {\n"
"    background:transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(169, 168, 181, 30);\n"
"}")
        self.pasteButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pasteButton.setIcon(icon1)
        self.pasteButton.setIconSize(QtCore.QSize(32, 32))
        self.pasteButton.setObjectName("pasteButton")
        self.copyButton = QtWidgets.QPushButton(self.centralwidget)
        self.copyButton.setGeometry(QtCore.QRect(520, 400, 41, 41))
        self.copyButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copyButton.setMouseTracking(True)
        self.copyButton.setStyleSheet("QPushButton {\n"
"    background:transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(169, 168, 181, 30);\n"
"}")
        self.copyButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyButton.setIcon(icon2)
        self.copyButton.setIconSize(QtCore.QSize(32, 32))
        self.copyButton.setObjectName("copyButton")
        self.notificationLabel = QtWidgets.QLabel(self.centralwidget)
        self.notificationLabel.setGeometry(QtCore.QRect(300, 590, 101, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notificationLabel.sizePolicy().hasHeightForWidth())
        self.notificationLabel.setSizePolicy(sizePolicy)
        self.notificationLabel.setMinimumSize(QtCore.QSize(3, 0))
        self.notificationLabel.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: white;\n"
"    border-radius: 20px\n"
"    opacity: 0\n"
"}")
        self.notificationLabel.setObjectName("notificationLabel")
        self.notificationLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.notificationLabel_2.setGeometry(QtCore.QRect(300, 590, 101, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notificationLabel_2.sizePolicy().hasHeightForWidth())
        self.notificationLabel_2.setSizePolicy(sizePolicy)
        self.notificationLabel_2.setMinimumSize(QtCore.QSize(3, 0))
        self.notificationLabel_2.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: white;\n"
"    border-radius: 20px\n"
"    opacity: 0\n"
"}")
        self.notificationLabel_2.setObjectName("notificationLabel_2")
        self.notificationLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.notificationLabel_3.setGeometry(QtCore.QRect(300, 590, 101, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notificationLabel_3.sizePolicy().hasHeightForWidth())
        self.notificationLabel_3.setSizePolicy(sizePolicy)
        self.notificationLabel_3.setMinimumSize(QtCore.QSize(3, 0))
        self.notificationLabel_3.setMouseTracking(True)
        self.notificationLabel_3.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: white;\n"
"    border-radius: 20px\n"
"    opacity: 0\n"
"}")
        self.notificationLabel_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.notificationLabel_3.setObjectName("notificationLabel_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bionic-Read Conventer"))
        self.inputTextBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.outputTextBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.convertButton.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Convert</p></body></html>"))
        self.header.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Bionic-Read Conventer</span></p></body></html>"))
        self.typeSelector.setToolTip(_translate("MainWindow", "Select your output type"))
        self.typeSelector.setCurrentText(_translate("MainWindow", "For HTML"))
        self.typeSelector.setItemText(0, _translate("MainWindow", "For HTML"))
        self.typeSelector.setItemText(1, _translate("MainWindow", "For Python"))
        self.typeSelector.setItemText(2, _translate("MainWindow", "For Direct"))
        self.pasteButton.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Paste</p></body></html>"))
        self.copyButton.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Copy</p></body></html>"))